<?php

namespace AppBundle\Repository;

use Doctrine\DBAL\Query\QueryBuilder;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * FilteredEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class FilteredEntityRepository extends EntityRepository {
  public function filter($params) {
    $qb = $this->createQueryBuilder('entity');

    foreach ($this->getFilterFields() as $field) {
      if (array_key_exists($field, $params)) {
        $value = $params[$field];

        if (is_numeric($value) || !empty($value)) {
          $qb
            ->andWhere("entity.$field = :{$field}_value")
            ->setParameter($field.'_value', $value);
        }
      }
    }

    if (!empty($params['sortBy'])) {
      $sort = $params['sortBy'];
    }
    else {
      $sort = 'dateCreated';
    }

    if (!empty($params['sortOrder'])) {
      $order = $params['sortOrder'];
    }
    else {
      $order = 'DESC';
    }

    $qb->orderBy("entity.$sort", $order);

    return $qb;
  }

  public abstract function getFilterFields();
}
