<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IssuePriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssuePriorityRepository extends EntityRepository {

}
