<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IssueStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueStatusRepository extends EntityRepository {

}
